version: "3.7"

services:
  python:
    container_name: python
    build: python/.
    volumes:
      - ./python:/code
    command: ["tail", "-f", "/dev/null"]

  javascript:
    container_name: javascript
    build: javascript/.
    volumes:
      - ./javascript:/code
      - /code/node_modules
    command: ["tail", "-f", "/dev/null"]

  puppeteer:
    container_name: puppeteer
    build: puppeteer/.
    volumes:
      - ./puppeteer:/code
      - /code/node_modules
    command: ["tail", "-f", "/dev/null"]
